name: Auto Commit

on:
  schedule:
    - cron: '0 12 * * *' # Every day at 12:00 UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Auto commit to keep GitHub green"
          git push
